# Generated by Django 5.0.6 on 2026-06-25 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio de Sesión')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Sesión')),
                ('device_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Información del Dispositivo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Detección',
                'verbose_name_plural': 'Sesiones de Detección',
            },
        ),
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', 'Feliz (happy)'), ('sad', 'Triste (sad)'), ('angry', 'Enojado (angry)'), ('surprise', 'Sorprendido (surprise)'), ('neutral', 'Neutral (neutral)'), ('fear', 'Temeroso (fear)'), ('disgust', 'Disgustado (disgust)')], max_length=20, verbose_name='Emoción')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Confianza (%)')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Detectado el')),
                ('face_bbox', models.JSONField(blank=True, null=True, verbose_name='Caja Delimitadora de Rostro (BBox)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='detection.detectionsession', verbose_name='Sesión de Detección')),
            ],
            options={
                'verbose_name': 'Registro de Emoción',
                'verbose_name_plural': 'Registros de Emociones',
            },
        ),
    ]
